apiVersion : apps/v1
kind: Deployment
metadata:
  name: "homepreviewapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homepreviewapp"
  template:
    metadata:
      labels:
        app: "homepreviewapp"
    spec:
      containers:
        - name: "homepreviewapp"
          image: "dev9w9eilatacr.azurecr.io/homepreviewapp:dev"
          ports:
          - containerPort: 80