apiVersion : apps/v1
kind: Deployment
metadata:
  name: "homepreviewapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homepreviewapp"
  template:
    metadata:
      labels:
        app: "homepreviewapp"
    spec:
      containers:
        - name: "homepreviewapp"
          image: "dev9w9eilatacr.azurecr.io/homepreviewapp:dev"
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "750m"