on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dev9w9eilatacr.azurecr.io
        username: ${{ secrets.acr_dev9w9eilatacr_username }}
        password: ${{ secrets.acr_dev9w9eilatacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/strapi" -f  "strapi/Dockerfile" -t dev9w9eilatacr.azurecr.io/devaks:${{ github.sha }}
        docker push dev9w9eilatacr.azurecr.io/devaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep development | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace development`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: development
        container-registry-url: dev9w9eilatacr.azurecr.io
        container-registry-username: ${{ secrets.acr_dev9w9eilatacr_username }}
        container-registry-password: ${{ secrets.acr_dev9w9eilatacr_password }}
        secret-name: devaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: development
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dev9w9eilatacr.azurecr.io/devaks:${{ github.sha }}
        imagepullsecrets: |
          devaksdockerauth