name: Manual Promote Strapi Dev->Test
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Check that the init is done by specific approved users of the Git repo.
    if: |
      github.actor == 'Cameron-Shaw' ||
      github.actor == 'Nick-Cunningham' ||
      github.actor == 'bashbang'
    steps:
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: dev9w9eilatacr.azurecr.io
        username: ${{ secrets.acr_dev9w9eilatacr_username }}
        password: ${{ secrets.acr_dev9w9eilatacr_password }}

    - name: Promote ACR image Dev->Test and push newly tagged image to ACR
      id: build-image
      run: |
        # TODO: This routine pulls the image, re-tags it, then re-pushes it.  There's deploy/load/bandwidth in the pull portion.
        # there doesn't seem to be an easy built in AZ way of added a tag to an already submitted image.
        # There actually is...but I'm not in love with the method:
        # It was designed for AWS, but there may be a way to do this with Azure: https://davin.ninja/amazon-ecr-adding-tag-image-already-pushed/
        # Basically it downloads the ECR manafest definition file then redeploys the same manafest file with a new tag.
        docker pull dev9w9eilatacr.azurecr.io/devaks:dev
        docker tag dev9w9eilatacr.azurecr.io/devaks:dev dev9w9eilatacr.azurecr.io/devaks:test
        docker push dev9w9eilatacr.azurecr.io/devaks:test
        # Bonus - This above method can easily be adapted for test->prod.  The manifest method won't work between different hosted ACRs.

    - name: Login to AKS
      uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devaks_kubeConfig }}
      id: login

    - name: Create namespace (if needed)
      run: |
        namespacePresent=`kubectl get namespace | grep development | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace development`
        fi

    - name: ACR to AKS secrets in place
      uses: azure/k8s-create-secret@v1
      with:
        namespace: testing
        container-registry-url: dev9w9eilatacr.azurecr.io
        container-registry-username: ${{ secrets.acr_dev9w9eilatacr_username }}
        container-registry-password: ${{ secrets.acr_dev9w9eilatacr_password }}
        secret-name: devaksdockerauth

    - name: Git Checkout   # Needed for manifests folder
      uses: actions/checkout@main

    - name: Update (or create) AKS deployments
      uses: azure/k8s-deploy@v1.3
      with:
        namespace: testing
        manifests: |
          manifests/deployment-strapi-test.yml
          manifests/service-strapi.yml
        images: |
          dev9w9eilatacr.azurecr.io/devaks:test
        imagepullsecrets: |
          devaksdockerauth
  permissions-failure:
    runs-on: ubuntu-latest
    if: github.actor == 'Cameron-Shaw' ||
        github.actor == 'Nick-Cunningham' ||
        github.actor == 'bashbang'
    steps:
    - name: Permissions Error
      run: |
        echo "You don't have permissions to run promote from dev to testing. Contact your administrator."
        exit 1
      id: permission-error
